version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: db_social
    env_file:
      - .env
    environment:
      POSTGRES_USER: social
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_database

  redis:
    image: redis:7
    container_name: redis_social

  fastapi:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_social
    command: ["./docker/app.sh"]
    depends_on:
      - postgres
      - redis
    ports:
      - 9999:8000

  celery:
    build:
      context: .
    container_name: celery_social
    command: ["./docker/celery.sh", "celery"]
    depends_on:
      - redis

  flower:
    build:
      context: .
    container_name: flower_social
    command: ["/social/docker/celery.sh", "flower"]
    depends_on:
      - celery
      - redis
    ports:
      - 8888:5555
