version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: db_social
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis_social

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    container_name: elasticsearch_social
    environment:
      - "discovery.type=single-node"

  fastapi:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_social
    entrypoint: ["sh", "-c"]
    command: ["alembic upgrade head && gunicorn social_media.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"]
    depends_on:
      - postgres
      - redis
      - elasticsearch
    ports:
      - 9999:8000

  celery:
    build:
      context: .
    env_file:
      - .env
    container_name: celery_social
    entrypoint: ["celery"]
    command: ["--app=tasks.tasks:celery", "worker", "-l", "INFO"]
    depends_on:
      - redis

  flower:
    build:
      context: .
    env_file:
      - .env
    container_name: flower_social
    entrypoint: ["celery"]
    command: ["--app=tasks.tasks:celery", "flower"]
    depends_on:
      - celery
      - redis
    ports:
      - 8888:5555
