"""made image field not required

Revision ID: 1824ec2c884b
Revises: 976cc4cc3961
Create Date: 2023-08-23 15:19:58.827685

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1824ec2c884b'
down_revision = '976cc4cc3961'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
