"""added subscription model

Revision ID: 214fc5ac39ae
Revises: c4dbb55a4af8
Create Date: 2023-07-14 22:08:40.049540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214fc5ac39ae'
down_revision = 'c4dbb55a4af8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=True),
    sa.Column('subscribed_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subscribed_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
