"""added user rel

Revision ID: 2a0202f5f56e
Revises: bdeb0d129612
Create Date: 2023-07-08 18:26:11.709195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a0202f5f56e'
down_revision = 'bdeb0d129612'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
