"""added reaction table

Revision ID: 360650e0afc0
Revises: 2a0202f5f56e
Create Date: 2023-07-09 01:03:39.112024

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '360650e0afc0'
down_revision = '2a0202f5f56e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'reactions', sa.Column('id', sa.Integer(), nullable=False), sa.Column('post_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True), sa.Column('reaction', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['post_id'],
            ['posts.id'],
        ), sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ), sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reactions_id'), 'reactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reactions_id'), table_name='reactions')
    op.drop_table('reactions')
    # ### end Alembic commands ###
