"""added created and updated fiedls

Revision ID: 3764e85fd1d4
Revises: 214fc5ac39ae
Create Date: 2023-07-20 00:54:55.029093

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3764e85fd1d4'
down_revision = '214fc5ac39ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'created_at')
    # ### end Alembic commands ###
