"""changed desc to text

Revision ID: 49b08882142f
Revises: a1d4a7319eb1
Create Date: 2023-07-23 02:17:31.464147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b08882142f'
down_revision = 'a1d4a7319eb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
