"""changed datetime to date

Revision ID: 840b69263874
Revises: 3764e85fd1d4
Create Date: 2023-07-20 00:59:41.082810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840b69263874'
down_revision = '3764e85fd1d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
