"""added comment response table

Revision ID: a1d4a7319eb1
Revises: 0aef916b45db
Create Date: 2023-07-22 02:13:20.786659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1d4a7319eb1'
down_revision = '0aef916b45db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'comment_responses', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('text', sa.String(), nullable=False), sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('comment_id', sa.Integer(), nullable=False), sa.ForeignKeyConstraint(
            ['comment_id'],
            ['comments.id'],
        ), sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ), sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_responses_id'), 'comment_responses', ['id'], unique=False)
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'revoked_tokens', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('jti', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='revoked_tokens_pkey'),
        sa.UniqueConstraint('jti', name='revoked_tokens_jti_key')
    )
    op.drop_index(op.f('ix_comment_responses_id'), table_name='comment_responses')
    op.drop_table('comment_responses')
    # ### end Alembic commands ###
