"""added views field to post table

Revision ID: c8a78befe351
Revises: 4b8d9d3c6dfd
Create Date: 2023-07-21 02:15:04.892527

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c8a78befe351'
down_revision = '4b8d9d3c6dfd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'views')
    # ### end Alembic commands ###
