"""added created at to comment

Revision ID: cfe350a4d53d
Revises: 49b08882142f
Create Date: 2023-07-29 00:21:02.825123

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cfe350a4d53d'
down_revision = '49b08882142f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_responses', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'created_at')
    op.drop_column('comment_responses', 'created_at')
    # ### end Alembic commands ###
